// <auto-generated />
using System;
using Gorevcim.Repository.AppDbContexts.AppDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gorevcim.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221019131956_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Gorevcim.Core.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("ActiveDateUpdate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<int>("IsActive")
                        .HasColumnType("int");

                    b.Property<DateTime>("IsActiveDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IsActiveDateUpdateUserId")
                        .HasColumnType("int");

                    b.Property<int>("IsActiveDateUserId")
                        .HasColumnType("int");

                    b.Property<int>("IsDelete")
                        .HasColumnType("int");

                    b.Property<DateTime>("IsDeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IsDeleteDateUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IsDeleteDateUpdateUserId")
                        .HasColumnType("int");

                    b.Property<int>("IsDeleteDateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActiveDateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateUserId = 0,
                            IsActive = 0,
                            IsActiveDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActiveDateUpdateUserId = 0,
                            IsActiveDateUserId = 0,
                            IsDelete = 0,
                            IsDeleteDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleteDateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleteDateUpdateUserId = 0,
                            IsDeleteDateUserId = 0,
                            Name = "Ofis Ürünleri",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdateUserId = 0
                        },
                        new
                        {
                            Id = 2,
                            ActiveDateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateUserId = 0,
                            IsActive = 0,
                            IsActiveDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActiveDateUpdateUserId = 0,
                            IsActiveDateUserId = 0,
                            IsDelete = 0,
                            IsDeleteDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleteDateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleteDateUpdateUserId = 0,
                            IsDeleteDateUserId = 0,
                            Name = "Polen Haşere",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdateUserId = 0
                        },
                        new
                        {
                            Id = 3,
                            ActiveDateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateUserId = 0,
                            IsActive = 0,
                            IsActiveDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActiveDateUpdateUserId = 0,
                            IsActiveDateUserId = 0,
                            IsDelete = 0,
                            IsDeleteDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleteDateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleteDateUpdateUserId = 0,
                            IsDeleteDateUserId = 0,
                            Name = "İzolasyon",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdateUserId = 0
                        },
                        new
                        {
                            Id = 4,
                            ActiveDateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateUserId = 0,
                            IsActive = 0,
                            IsActiveDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActiveDateUpdateUserId = 0,
                            IsActiveDateUserId = 0,
                            IsDelete = 0,
                            IsDeleteDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleteDateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleteDateUpdateUserId = 0,
                            IsDeleteDateUserId = 0,
                            Name = "Polen Delici",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdateUserId = 0
                        },
                        new
                        {
                            Id = 5,
                            ActiveDateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateUserId = 0,
                            IsActive = 0,
                            IsActiveDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActiveDateUpdateUserId = 0,
                            IsActiveDateUserId = 0,
                            IsDelete = 0,
                            IsDeleteDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleteDateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleteDateUpdateUserId = 0,
                            IsDeleteDateUserId = 0,
                            Name = "Montaj Asma",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdateUserId = 0
                        },
                        new
                        {
                            Id = 6,
                            ActiveDateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateUserId = 0,
                            IsActive = 0,
                            IsActiveDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActiveDateUpdateUserId = 0,
                            IsActiveDateUserId = 0,
                            IsDelete = 0,
                            IsDeleteDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleteDateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleteDateUpdateUserId = 0,
                            IsDeleteDateUserId = 0,
                            Name = "Tadilat",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdateUserId = 0
                        },
                        new
                        {
                            Id = 7,
                            ActiveDateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateUserId = 0,
                            IsActive = 0,
                            IsActiveDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActiveDateUpdateUserId = 0,
                            IsActiveDateUserId = 0,
                            IsDelete = 0,
                            IsDeleteDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleteDateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleteDateUpdateUserId = 0,
                            IsDeleteDateUserId = 0,
                            Name = "Tamir",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdateUserId = 0
                        },
                        new
                        {
                            Id = 8,
                            ActiveDateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateUserId = 0,
                            IsActive = 0,
                            IsActiveDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActiveDateUpdateUserId = 0,
                            IsActiveDateUserId = 0,
                            IsDelete = 0,
                            IsDeleteDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleteDateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleteDateUpdateUserId = 0,
                            IsDeleteDateUserId = 0,
                            Name = "Maskeleme ",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdateUserId = 0
                        },
                        new
                        {
                            Id = 9,
                            ActiveDateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateUserId = 0,
                            IsActive = 0,
                            IsActiveDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActiveDateUpdateUserId = 0,
                            IsActiveDateUserId = 0,
                            IsDelete = 0,
                            IsDeleteDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleteDateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleteDateUpdateUserId = 0,
                            IsDeleteDateUserId = 0,
                            Name = "Kaydırmaz",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdateUserId = 0
                        },
                        new
                        {
                            Id = 10,
                            ActiveDateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateUserId = 0,
                            IsActive = 0,
                            IsActiveDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActiveDateUpdateUserId = 0,
                            IsActiveDateUserId = 0,
                            IsDelete = 0,
                            IsDeleteDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleteDateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleteDateUpdateUserId = 0,
                            IsDeleteDateUserId = 0,
                            Name = "İç Cephe Boyalar",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdateUserId = 0
                        },
                        new
                        {
                            Id = 11,
                            ActiveDateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateUserId = 0,
                            IsActive = 0,
                            IsActiveDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActiveDateUpdateUserId = 0,
                            IsActiveDateUserId = 0,
                            IsDelete = 0,
                            IsDeleteDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleteDateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleteDateUpdateUserId = 0,
                            IsDeleteDateUserId = 0,
                            Name = "Dış Cephe Boyalar",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdateUserId = 0
                        },
                        new
                        {
                            Id = 12,
                            ActiveDateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateUserId = 0,
                            IsActive = 0,
                            IsActiveDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActiveDateUpdateUserId = 0,
                            IsActiveDateUserId = 0,
                            IsDelete = 0,
                            IsDeleteDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleteDateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleteDateUpdateUserId = 0,
                            IsDeleteDateUserId = 0,
                            Name = "Tinerler",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdateUserId = 0
                        });
                });

            modelBuilder.Entity("Gorevcim.Core.ProductBrands", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("ActiveDateUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BrandsName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BrandsWebUrl")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Explanation")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("IsActive")
                        .HasColumnType("int");

                    b.Property<DateTime>("IsActiveDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IsActiveDateUpdateUserId")
                        .HasColumnType("int");

                    b.Property<int>("IsActiveDateUserId")
                        .HasColumnType("int");

                    b.Property<int>("IsDelete")
                        .HasColumnType("int");

                    b.Property<DateTime>("IsDeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IsDeleteDateUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IsDeleteDateUpdateUserId")
                        .HasColumnType("int");

                    b.Property<int>("IsDeleteDateUserId")
                        .HasColumnType("int");

                    b.Property<string>("LogoBase64Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoFileName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LogoFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ProductFeaturesId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductFeaturesId")
                        .IsUnique();

                    b.ToTable("ProductBrands");
                });

            modelBuilder.Entity("Gorevcim.Core.ProductColors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("ActiveDateUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ColorBase64Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColorFileName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ColorFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Explanation")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("IsActive")
                        .HasColumnType("int");

                    b.Property<DateTime>("IsActiveDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IsActiveDateUpdateUserId")
                        .HasColumnType("int");

                    b.Property<int>("IsActiveDateUserId")
                        .HasColumnType("int");

                    b.Property<int>("IsDelete")
                        .HasColumnType("int");

                    b.Property<DateTime>("IsDeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IsDeleteDateUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IsDeleteDateUpdateUserId")
                        .HasColumnType("int");

                    b.Property<int>("IsDeleteDateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProductFeaturesId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductFeaturesId")
                        .IsUnique();

                    b.ToTable("ProductColors");
                });

            modelBuilder.Entity("Gorevcim.Core.ProductCurrencyUnits", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("ActiveDateUpdate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Explanation")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("IsActive")
                        .HasColumnType("int");

                    b.Property<DateTime>("IsActiveDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IsActiveDateUpdateUserId")
                        .HasColumnType("int");

                    b.Property<int>("IsActiveDateUserId")
                        .HasColumnType("int");

                    b.Property<int>("IsDelete")
                        .HasColumnType("int");

                    b.Property<DateTime>("IsDeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IsDeleteDateUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IsDeleteDateUpdateUserId")
                        .HasColumnType("int");

                    b.Property<int>("IsDeleteDateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProductFeaturesId")
                        .HasColumnType("int");

                    b.Property<string>("ShortCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductFeaturesId")
                        .IsUnique();

                    b.ToTable("ProductCurrencyUnits");
                });

            modelBuilder.Entity("Gorevcim.Core.ProductFeatures", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("ActiveDateUpdate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<int>("IsActive")
                        .HasColumnType("int");

                    b.Property<DateTime>("IsActiveDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IsActiveDateUpdateUserId")
                        .HasColumnType("int");

                    b.Property<int>("IsActiveDateUserId")
                        .HasColumnType("int");

                    b.Property<int>("IsDelete")
                        .HasColumnType("int");

                    b.Property<DateTime>("IsDeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IsDeleteDateUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IsDeleteDateUpdateUserId")
                        .HasColumnType("int");

                    b.Property<int>("IsDeleteDateUserId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("ProductFeatures");
                });

            modelBuilder.Entity("Gorevcim.Core.ProductMeasurementUnits", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("ActiveDateUpdate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Explanation")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("IsActive")
                        .HasColumnType("int");

                    b.Property<DateTime>("IsActiveDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IsActiveDateUpdateUserId")
                        .HasColumnType("int");

                    b.Property<int>("IsActiveDateUserId")
                        .HasColumnType("int");

                    b.Property<int>("IsDelete")
                        .HasColumnType("int");

                    b.Property<DateTime>("IsDeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IsDeleteDateUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IsDeleteDateUpdateUserId")
                        .HasColumnType("int");

                    b.Property<int>("IsDeleteDateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProductFeaturesId")
                        .HasColumnType("int");

                    b.Property<string>("ShortCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductFeaturesId")
                        .IsUnique();

                    b.ToTable("ProductMeasurementUnits");
                });

            modelBuilder.Entity("Gorevcim.Core.ProductProjects", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("ActiveDateUpdate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Explanation")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("IsActive")
                        .HasColumnType("int");

                    b.Property<DateTime>("IsActiveDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IsActiveDateUpdateUserId")
                        .HasColumnType("int");

                    b.Property<int>("IsActiveDateUserId")
                        .HasColumnType("int");

                    b.Property<int>("IsDelete")
                        .HasColumnType("int");

                    b.Property<DateTime>("IsDeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IsDeleteDateUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IsDeleteDateUpdateUserId")
                        .HasColumnType("int");

                    b.Property<int>("IsDeleteDateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProductFeaturesId")
                        .HasColumnType("int");

                    b.Property<string>("ShortCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductFeaturesId")
                        .IsUnique();

                    b.ToTable("ProductProjects");
                });

            modelBuilder.Entity("Gorevcim.Core.Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("ActiveDateUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Barcode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Explanation")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ExplanationWebUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("IsActive")
                        .HasColumnType("int");

                    b.Property<DateTime>("IsActiveDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IsActiveDateUpdateUserId")
                        .HasColumnType("int");

                    b.Property<int>("IsActiveDateUserId")
                        .HasColumnType("int");

                    b.Property<int>("IsDelete")
                        .HasColumnType("int");

                    b.Property<DateTime>("IsDeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IsDeleteDateUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IsDeleteDateUpdateUserId")
                        .HasColumnType("int");

                    b.Property<int>("IsDeleteDateUserId")
                        .HasColumnType("int");

                    b.Property<int>("IsMixture")
                        .HasColumnType("int");

                    b.Property<string>("LogoBase64Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoFileName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LogoFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("TechnicalWebUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActiveDateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Barcode = "AS123",
                            CategoryId = 1,
                            Code = "123AS",
                            CreateDate = new DateTime(2022, 10, 19, 16, 19, 56, 156, DateTimeKind.Local).AddTicks(3359),
                            CreateUserId = 0,
                            ExpirationDate = new DateTime(2022, 10, 19, 16, 19, 56, 156, DateTimeKind.Local).AddTicks(3344),
                            Explanation = "hghghgh",
                            ExplanationWebUrl = "dlld",
                            IsActive = 0,
                            IsActiveDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActiveDateUpdateUserId = 0,
                            IsActiveDateUserId = 0,
                            IsDelete = 0,
                            IsDeleteDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleteDateUpdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleteDateUpdateUserId = 0,
                            IsDeleteDateUserId = 0,
                            IsMixture = 1,
                            LogoBase64Content = "ad",
                            LogoFileName = "sdf",
                            LogoFilePath = "sdsdf",
                            Name = "Test Ürün1",
                            PurchasePrice = 10m,
                            SalePrice = 15m,
                            Stock = 1,
                            TechnicalWebUrl = "dfsd",
                            UpdateDate = new DateTime(2022, 10, 19, 16, 19, 56, 156, DateTimeKind.Local).AddTicks(3360),
                            UpdateUserId = 0
                        });
                });

            modelBuilder.Entity("Gorevcim.Core.ProductVatUnits", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("ActiveDateUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Explanation")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("IsActive")
                        .HasColumnType("int");

                    b.Property<DateTime>("IsActiveDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IsActiveDateUpdateUserId")
                        .HasColumnType("int");

                    b.Property<int>("IsActiveDateUserId")
                        .HasColumnType("int");

                    b.Property<int>("IsDelete")
                        .HasColumnType("int");

                    b.Property<DateTime>("IsDeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IsDeleteDateUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IsDeleteDateUpdateUserId")
                        .HasColumnType("int");

                    b.Property<int>("IsDeleteDateUserId")
                        .HasColumnType("int");

                    b.Property<int>("IsExemption")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProductFeaturesId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductFeaturesId")
                        .IsUnique();

                    b.ToTable("ProductVatUnits");
                });

            modelBuilder.Entity("Gorevcim.Core.ProductWeightUnits", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("ActiveDateUpdate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Explanation")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("IsActive")
                        .HasColumnType("int");

                    b.Property<DateTime>("IsActiveDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IsActiveDateUpdateUserId")
                        .HasColumnType("int");

                    b.Property<int>("IsActiveDateUserId")
                        .HasColumnType("int");

                    b.Property<int>("IsDelete")
                        .HasColumnType("int");

                    b.Property<DateTime>("IsDeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IsDeleteDateUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IsDeleteDateUpdateUserId")
                        .HasColumnType("int");

                    b.Property<int>("IsDeleteDateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProductFeaturesId")
                        .HasColumnType("int");

                    b.Property<string>("ShortCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductFeaturesId")
                        .IsUnique();

                    b.ToTable("ProductWeightUnits");
                });

            modelBuilder.Entity("Gorevcim.Core.ProductBrands", b =>
                {
                    b.HasOne("Gorevcim.Core.ProductFeatures", "ProductFeatures")
                        .WithOne("ProductBrands")
                        .HasForeignKey("Gorevcim.Core.ProductBrands", "ProductFeaturesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductFeatures");
                });

            modelBuilder.Entity("Gorevcim.Core.ProductColors", b =>
                {
                    b.HasOne("Gorevcim.Core.ProductFeatures", "ProductFeatures")
                        .WithOne("ProductColors")
                        .HasForeignKey("Gorevcim.Core.ProductColors", "ProductFeaturesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductFeatures");
                });

            modelBuilder.Entity("Gorevcim.Core.ProductCurrencyUnits", b =>
                {
                    b.HasOne("Gorevcim.Core.ProductFeatures", "ProductFeatures")
                        .WithOne("ProductCurrencyUnits")
                        .HasForeignKey("Gorevcim.Core.ProductCurrencyUnits", "ProductFeaturesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductFeatures");
                });

            modelBuilder.Entity("Gorevcim.Core.ProductFeatures", b =>
                {
                    b.HasOne("Gorevcim.Core.Products", "Products")
                        .WithOne("ProductFeatures")
                        .HasForeignKey("Gorevcim.Core.ProductFeatures", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Gorevcim.Core.ProductMeasurementUnits", b =>
                {
                    b.HasOne("Gorevcim.Core.ProductFeatures", "ProductFeatures")
                        .WithOne("ProductMeasurementUnits")
                        .HasForeignKey("Gorevcim.Core.ProductMeasurementUnits", "ProductFeaturesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductFeatures");
                });

            modelBuilder.Entity("Gorevcim.Core.ProductProjects", b =>
                {
                    b.HasOne("Gorevcim.Core.ProductFeatures", "ProductFeatures")
                        .WithOne("ProductProjects")
                        .HasForeignKey("Gorevcim.Core.ProductProjects", "ProductFeaturesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductFeatures");
                });

            modelBuilder.Entity("Gorevcim.Core.Products", b =>
                {
                    b.HasOne("Gorevcim.Core.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Gorevcim.Core.ProductVatUnits", b =>
                {
                    b.HasOne("Gorevcim.Core.ProductFeatures", "ProductFeatures")
                        .WithOne("ProductVatUnits")
                        .HasForeignKey("Gorevcim.Core.ProductVatUnits", "ProductFeaturesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductFeatures");
                });

            modelBuilder.Entity("Gorevcim.Core.ProductWeightUnits", b =>
                {
                    b.HasOne("Gorevcim.Core.ProductFeatures", "ProductFeatures")
                        .WithOne("ProductWeightUnits")
                        .HasForeignKey("Gorevcim.Core.ProductWeightUnits", "ProductFeaturesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductFeatures");
                });

            modelBuilder.Entity("Gorevcim.Core.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Gorevcim.Core.ProductFeatures", b =>
                {
                    b.Navigation("ProductBrands")
                        .IsRequired();

                    b.Navigation("ProductColors")
                        .IsRequired();

                    b.Navigation("ProductCurrencyUnits")
                        .IsRequired();

                    b.Navigation("ProductMeasurementUnits")
                        .IsRequired();

                    b.Navigation("ProductProjects")
                        .IsRequired();

                    b.Navigation("ProductVatUnits")
                        .IsRequired();

                    b.Navigation("ProductWeightUnits")
                        .IsRequired();
                });

            modelBuilder.Entity("Gorevcim.Core.Products", b =>
                {
                    b.Navigation("ProductFeatures")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
